services:

  php:
    restart: always
    image: ghcr.io/geekcodev/php:8.4-bookworm
    user: 1000:1000
    volumes:
      - ./:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TZ=Europe/Moscow
