<?php

declare(strict_types=1);

namespace GeekCo\CommerceJson\Enums;

use InvalidArgumentException;
use JsonSerializable;

enum CurrencyEnum: string implements JsonSerializable
{
    case AED = 'AED';
    case AFN = 'AFN';
    case ALL = 'ALL';
    case AMD = 'AMD';
    case ANG = 'ANG';
    case AOA = 'AOA';
    case ARS = 'ARS';
    case AUD = 'AUD';
    case AWG = 'AWG';
    case AZN = 'AZN';
    case BAM = 'BAM';
    case BBD = 'BBD';
    case BDT = 'BDT';
    case BGN = 'BGN';
    case BHD = 'BHD';
    case BIF = 'BIF';
    case BMD = 'BMD';
    case BND = 'BND';
    case BOB = 'BOB';
    case BOV = 'BOV';
    case BRL = 'BRL';
    case BSD = 'BSD';
    case BTN = 'BTN';
    case BWP = 'BWP';
    case BYN = 'BYN';
    case BZD = 'BZD';
    case CAD = 'CAD';
    case CDF = 'CDF';
    case CHE = 'CHE';
    case CHF = 'CHF';
    case CHW = 'CHW';
    case CLF = 'CLF';
    case CLP = 'CLP';
    case CNY = 'CNY';
    case COP = 'COP';
    case COU = 'COU';
    case CRC = 'CRC';
    case CUC = 'CUC';
    case CUP = 'CUP';
    case CVE = 'CVE';
    case CZK = 'CZK';
    case DJF = 'DJF';
    case DKK = 'DKK';
    case DOP = 'DOP';
    case DZD = 'DZD';
    case EGP = 'EGP';
    case ERN = 'ERN';
    case ETB = 'ETB';
    case EUR = 'EUR';
    case FJD = 'FJD';
    case FKP = 'FKP';
    case GBP = 'GBP';
    case GEL = 'GEL';
    case GHS = 'GHS';
    case GIP = 'GIP';
    case GMD = 'GMD';
    case GNF = 'GNF';
    case GTQ = 'GTQ';
    case GYD = 'GYD';
    case HKD = 'HKD';
    case HNL = 'HNL';
    case HTG = 'HTG';
    case HUF = 'HUF';
    case IDR = 'IDR';
    case ILS = 'ILS';
    case INR = 'INR';
    case IQD = 'IQD';
    case IRR = 'IRR';
    case ISK = 'ISK';
    case JMD = 'JMD';
    case JOD = 'JOD';
    case JPY = 'JPY';
    case KES = 'KES';
    case KGS = 'KGS';
    case KHR = 'KHR';
    case KMF = 'KMF';
    case KPW = 'KPW';
    case KRW = 'KRW';
    case KWD = 'KWD';
    case KYD = 'KYD';
    case KZT = 'KZT';
    case LAK = 'LAK';
    case LBP = 'LBP';
    case LKR = 'LKR';
    case LRD = 'LRD';
    case LSL = 'LSL';
    case LYD = 'LYD';
    case MAD = 'MAD';
    case MDL = 'MDL';
    case MGA = 'MGA';
    case MKD = 'MKD';
    case MMK = 'MMK';
    case MNT = 'MNT';
    case MOP = 'MOP';
    case MRU = 'MRU';
    case MUR = 'MUR';
    case MVR = 'MVR';
    case MWK = 'MWK';
    case MXN = 'MXN';
    case MXV = 'MXV';
    case MZN = 'MZN';
    case NAD = 'NAD';
    case NGN = 'NGN';
    case NIO = 'NIO';
    case NOK = 'NOK';
    case NPR = 'NPR';
    case NZD = 'NZD';
    case OMR = 'OMR';
    case PAB = 'PAB';
    case PEN = 'PEN';
    case PGK = 'PGK';
    case PHP = 'PHP';
    case PKR = 'PKR';
    case PLN = 'PLN';
    case PYG = 'PYG';
    case QAR = 'QAR';
    case RON = 'RON';
    case RSD = 'RSD';
    case RUB = 'RUB';
    case RWF = 'RWF';
    case SAR = 'SAR';
    case SBD = 'SBD';
    case SCR = 'SCR';
    case SDG = 'SDG';
    case SEK = 'SEK';
    case SGD = 'SGD';
    case SHP = 'SHP';
    case SLL = 'SLL';
    case SOS = 'SOS';
    case SRD = 'SRD';
    case SSP = 'SSP';
    case STN = 'STN';
    case SVC = 'SVC';
    case SYP = 'SYP';
    case SZL = 'SZL';
    case THB = 'THB';
    case TJS = 'TJS';
    case TMT = 'TMT';
    case TND = 'TND';
    case TOP = 'TOP';
    case TRY = 'TRY';
    case TTD = 'TTD';
    case TWD = 'TWD';
    case TZS = 'TZS';
    case UAH = 'UAH';
    case UGX = 'UGX';
    case USD = 'USD';
    case USN = 'USN';
    case UYI = 'UYI';
    case UYU = 'UYU';
    case UZS = 'UZS';
    case VES = 'VES';
    case VND = 'VND';
    case VUV = 'VUV';
    case WST = 'WST';
    case XAF = 'XAF';
    case XCD = 'XCD';
    case XDR = 'XDR';
    case XOF = 'XOF';
    case XPF = 'XPF';
    case XSU = 'XSU';
    case XUA = 'XUA';
    case YER = 'YER';
    case ZAR = 'ZAR';
    case ZMW = 'ZMW';
    case ZWL = 'ZWL';

    /** Английские названия валют */
    private const array NAMES_EN = [
        'AED' => 'UAE Dirham',
        'AFN' => 'Afghan Afghani',
        'ALL' => 'Albanian Lek',
        'AMD' => 'Armenian Dram',
        'ANG' => 'Netherlands Antillean Guilder',
        'AOA' => 'Angolan Kwanza',
        'ARS' => 'Argentine Peso',
        'AUD' => 'Australian Dollar',
        'AWG' => 'Aruban Florin',
        'AZN' => 'Azerbaijani Manat',
        'BAM' => 'Bosnia-Herzegovina Convertible Mark',
        'BBD' => 'Barbadian Dollar',
        'BDT' => 'Bangladeshi Taka',
        'BGN' => 'Bulgarian Lev',
        'BHD' => 'Bahraini Dinar',
        'BIF' => 'Burundian Franc',
        'BMD' => 'Bermudian Dollar',
        'BND' => 'Brunei Dollar',
        'BOB' => 'Bolivian Boliviano',
        'BOV' => 'Bolivian Mvdol',
        'BRL' => 'Brazilian Real',
        'BSD' => 'Bahamian Dollar',
        'BTN' => 'Bhutanese Ngultrum',
        'BWP' => 'Botswana Pula',
        'BYN' => 'Belarusian Ruble',
        'BZD' => 'Belize Dollar',
        'CAD' => 'Canadian Dollar',
        'CDF' => 'Congolese Franc',
        'CHE' => 'WIR Euro',
        'CHF' => 'Swiss Franc',
        'CHW' => 'WIR Franc',
        'CLF' => 'Chilean Unit of Account (UF)',
        'CLP' => 'Chilean Peso',
        'CNY' => 'Chinese Yuan',
        'COP' => 'Colombian Peso',
        'COU' => 'Colombian Real Value Unit',
        'CRC' => 'Costa Rican Colón',
        'CUC' => 'Cuban Convertible Peso',
        'CUP' => 'Cuban Peso',
        'CVE' => 'Cape Verdean Escudo',
        'CZK' => 'Czech Koruna',
        'DJF' => 'Djiboutian Franc',
        'DKK' => 'Danish Krone',
        'DOP' => 'Dominican Peso',
        'DZD' => 'Algerian Dinar',
        'EGP' => 'Egyptian Pound',
        'ERN' => 'Eritrean Nakfa',
        'ETB' => 'Ethiopian Birr',
        'EUR' => 'Euro',
        'FJD' => 'Fijian Dollar',
        'FKP' => 'Falkland Islands Pound',
        'GBP' => 'Pound Sterling',
        'GEL' => 'Georgian Lari',
        'GHS' => 'Ghanaian Cedi',
        'GIP' => 'Gibraltar Pound',
        'GMD' => 'Gambian Dalasi',
        'GNF' => 'Guinean Franc',
        'GTQ' => 'Guatemalan Quetzal',
        'GYD' => 'Guyanese Dollar',
        'HKD' => 'Hong Kong Dollar',
        'HNL' => 'Honduran Lempira',
        'HTG' => 'Haitian Gourde',
        'HUF' => 'Hungarian Forint',
        'IDR' => 'Indonesian Rupiah',
        'ILS' => 'Israeli New Shekel',
        'INR' => 'Indian Rupee',
        'IQD' => 'Iraqi Dinar',
        'IRR' => 'Iranian Rial',
        'ISK' => 'Icelandic Króna',
        'JMD' => 'Jamaican Dollar',
        'JOD' => 'Jordanian Dinar',
        'JPY' => 'Japanese Yen',
        'KES' => 'Kenyan Shilling',
        'KGS' => 'Kyrgyzstani Som',
        'KHR' => 'Cambodian Riel',
        'KMF' => 'Comorian Franc',
        'KPW' => 'North Korean Won',
        'KRW' => 'South Korean Won',
        'KWD' => 'Kuwaiti Dinar',
        'KYD' => 'Cayman Islands Dollar',
        'KZT' => 'Kazakhstani Tenge',
        'LAK' => 'Lao Kip',
        'LBP' => 'Lebanese Pound',
        'LKR' => 'Sri Lankan Rupee',
        'LRD' => 'Liberian Dollar',
        'LSL' => 'Lesotho Loti',
        'LYD' => 'Libyan Dinar',
        'MAD' => 'Moroccan Dirham',
        'MDL' => 'Moldovan Leu',
        'MGA' => 'Malagasy Ariary',
        'MKD' => 'Macedonian Denar',
        'MMK' => 'Myanmar Kyat',
        'MNT' => 'Mongolian Tögrög',
        'MOP' => 'Macanese Pataca',
        'MRU' => 'Mauritanian Ouguiya',
        'MUR' => 'Mauritian Rupee',
        'MVR' => 'Maldivian Rufiyaa',
        'MWK' => 'Malawian Kwacha',
        'MXN' => 'Mexican Peso',
        'MXV' => 'Mexican UDI',
        'MZN' => 'Mozambican Metical',
        'NAD' => 'Namibian Dollar',
        'NGN' => 'Nigerian Naira',
        'NIO' => 'Nicaraguan Córdoba',
        'NOK' => 'Norwegian Krone',
        'NPR' => 'Nepalese Rupee',
        'NZD' => 'New Zealand Dollar',
        'OMR' => 'Omani Rial',
        'PAB' => 'Panamanian Balboa',
        'PEN' => 'Peruvian Sol',
        'PGK' => 'Papua New Guinean Kina',
        'PHP' => 'Philippine Peso',
        'PKR' => 'Pakistani Rupee',
        'PLN' => 'Polish Złoty',
        'PYG' => 'Paraguayan Guarani',
        'QAR' => 'Qatari Riyal',
        'RON' => 'Romanian Leu',
        'RSD' => 'Serbian Dinar',
        'RUB' => 'Russian Ruble',
        'RWF' => 'Rwandan Franc',
        'SAR' => 'Saudi Riyal',
        'SBD' => 'Solomon Islands Dollar',
        'SCR' => 'Seychellois Rupee',
        'SDG' => 'Sudanese Pound',
        'SEK' => 'Swedish Krona',
        'SGD' => 'Singapore Dollar',
        'SHP' => 'Saint Helena Pound',
        'SLL' => 'Sierra Leonean Leone',
        'SOS' => 'Somali Shilling',
        'SRD' => 'Surinamese Dollar',
        'SSP' => 'South Sudanese Pound',
        'STN' => 'São Tomé and Príncipe Dobra',
        'SVC' => 'Salvadoran Colón',
        'SYP' => 'Syrian Pound',
        'SZL' => 'Swazi Lilangeni',
        'THB' => 'Thai Baht',
        'TJS' => 'Tajikistani Somoni',
        'TMT' => 'Turkmenistan Manat',
        'TND' => 'Tunisian Dinar',
        'TOP' => 'Tongan Paʻanga',
        'TRY' => 'Turkish Lira',
        'TTD' => 'Trinidad and Tobago Dollar',
        'TWD' => 'New Taiwan Dollar',
        'TZS' => 'Tanzanian Shilling',
        'UAH' => 'Ukrainian Hryvnia',
        'UGX' => 'Ugandan Shilling',
        'USD' => 'United States Dollar',
        'USN' => 'United States Dollar (Next day)',
        'UYI' => 'Uruguayan Peso (URUIURUI)',
        'UYU' => 'Uruguayan Peso',
        'UZS' => 'Uzbekistani Som',
        'VES' => 'Venezuelan Bolívar',

        'VND' => 'Vietnamese Dong',
        'VUV' => 'Vanuatu Vatu',
        'WST' => 'Samoan Tala',
        'XAF' => 'CFA Franc BEAC',
        'XCD' => 'East Caribbean Dollar',
        'XDR' => 'Special Drawing Rights',
        'XOF' => 'CFA Franc BCEAO',
        'XPF' => 'CFP Franc',
        'XSU' => 'SUCRE',
        'XUA' => 'ADB Unit of Account',
        'YER' => 'Yemeni Rial',
        'ZAR' => 'South African Rand',
        'ZMW' => 'Zambian Kwacha',
        'ZWL' => 'Zimbabwean Dollar',
    ];

    private const array NAMES_RU = [
        'AED' => 'Дирхам ОАЭ',
        'AFN' => 'Афгани',
        'ALL' => 'Албанский лек',
        'AMD' => 'Армянский драм',
        'ANG' => 'Нидерландский антильский гульден',
        'AOA' => 'Ангольская кванза',
        'ARS' => 'Аргентинское песо',
        'AUD' => 'Австралийский доллар',
        'AWG' => 'Арубанский флорин',
        'AZN' => 'Азербайджанский манат',
        'BAM' => 'Конвертируемая марка Боснии и Герцеговины',
        'BBD' => 'Барбадосский доллар',
        'BDT' => 'Бангладешская така',
        'BGN' => 'Болгарский лев',
        'BHD' => 'Бахрейнский динар',
        'BIF' => 'Бурундийский франк',
        'BMD' => 'Бермудский доллар',
        'BND' => 'Брунейский доллар',
        'BOB' => 'Боливийский боливиано',
        'BOV' => 'Боливийский Mvdol',
        'BRL' => 'Бразильский реал',
        'BSD' => 'Багамский доллар',
        'BTN' => 'Бутанский нгултрум',
        'BWP' => 'Ботсванская пула',
        'BYN' => 'Белорусский рубль',
        'BZD' => 'Белизский доллар',
        'CAD' => 'Канадский доллар',
        'CDF' => 'Конголезский франк',
        'CHE' => 'WIR Евро',
        'CHF' => 'Швейцарский франк',
        'CHW' => 'WIR Франк',
        'CLF' => 'Унидад де Фоменто (Чили)',
        'CLP' => 'Чилийское песо',
        'CNY' => 'Китайский юань',
        'COP' => 'Колумбийское песо',
        'COU' => 'Унидад де валор реаль',
        'CRC' => 'Коста-риканский колон',
        'CUC' => 'Кубинское конвертируемое песо',
        'CUP' => 'Кубинское песо',
        'CVE' => 'Эскудо Кабо-Верде',
        'CZK' => 'Чешская крона',
        'DJF' => 'Джибутский франк',
        'DKK' => 'Датская крона',
        'DOP' => 'Доминиканское песо',
        'DZD' => 'Алжирский динар',
        'EGP' => 'Египетский фунт',
        'ERN' => 'Эритрейская накфа',
        'ETB' => 'Эфиопский быр',
        'EUR' => 'Евро',
        'FJD' => 'Фиджийский доллар',
        'FKP' => 'Фунт Фолклендских островов',
        'GBP' => 'Фунт стерлингов',
        'GEL' => 'Грузинский лари',
        'GHS' => 'Ганский седи',
        'GIP' => 'Гибралтарский фунт',
        'GMD' => 'Гамбийский даласи',
        'GNF' => 'Гвинейский франк',
        'GTQ' => 'Гватемальский кетсаль',
        'GYD' => 'Гайанский доллар',
        'HKD' => 'Гонконгский доллар',
        'HNL' => 'Гондурасская лемпира',
        'HTG' => 'Гаитянский гурд',
        'HUF' => 'Венгерский форинт',
        'IDR' => 'Индонезийская рупия',
        'ILS' => 'Новый израильский шекель',
        'INR' => 'Индийская рупия',
        'IQD' => 'Иракский динар',
        'IRR' => 'Иранский риал',
        'ISK' => 'Исландская крона',
        'JMD' => 'Ямайский доллар',
        'JOD' => 'Иорданский динар',
        'JPY' => 'Японская иена',
        'KES' => 'Кенийский шиллинг',
        'KGS' => 'Кыргызский сом',
        'KHR' => 'Камбоджийский риель',
        'KMF' => 'Коморский франк',
        'KPW' => 'Северокорейский вон',
        'KRW' => 'Южнокорейский вон',
        'KWD' => 'Кувейтский динар',
        'KYD' => 'Доллар Каймановых островов',
        'KZT' => 'Казахстанский тенге',
        'LAK' => 'Лаосский кип',
        'LBP' => 'Ливанский фунт',
        'LKR' => 'Шри-ланкийская рупия',
        'LRD' => 'Либерийский доллар',
        'LSL' => 'Лоти Лесото',
        'LYD' => 'Ливийский динар',
        'MAD' => 'Марокканский дирхам',
        'MDL' => 'Молдавский лей',
        'MGA' => 'Малагасийский ариари',
        'MKD' => 'Македонский денар',
        'MMK' => 'Мьянманский кьят',
        'MNT' => 'Монгольский тугрик',
        'MOP' => 'Патака Макао',
        'MRU' => 'Мавританская угия',
        'MUR' => 'Маврикийская рупия',
        'MVR' => 'Мальдивская руфия',
        'MWK' => 'Малавийская квача',
        'MXN' => 'Мексиканское песо',
        'MXV' => 'Мексиканский UDI',
        'MZN' => 'Мозамбикский метикал',
        'NAD' => 'Намибийский доллар',
        'NGN' => 'Нигерийская найра',
        'NIO' => 'Никарагуанская кордоба',
        'NOK' => 'Норвежская крона',
        'NPR' => 'Непальская рупия',
        'NZD' => 'Новозеландский доллар',
        'OMR' => 'Оманский риал',
        'PAB' => 'Панамский бальбоа',
        'PEN' => 'Перуанский соль',
        'PGK' => 'Кина Папуа — Новой Гвинеи',
        'PHP' => 'Филиппинское песо',
        'PKR' => 'Пакистанская рупия',
        'PLN' => 'Польский злотый',
        'PYG' => 'Парагвайский гуарани',
        'QAR' => 'Катарский риал',
        'RON' => 'Румынский лей',
        'RSD' => 'Сербский динар',
        'RUB' => 'Российский рубль',
        'RWF' => 'Руандийский франк',
        'SAR' => 'Саудовский риял',
        'SBD' => 'Доллар Соломоновых Островов',
        'SCR' => 'Сейшельская рупия',
        'SDG' => 'Суданский фунт',
        'SEK' => 'Шведская крона',
        'SGD' => 'Сингапурский доллар',
        'SHP' => 'Фунт Острова Святой Елены',
        'SLL' => 'Сьерра-леонский леоне',
        'SOS' => 'Сомалийский шиллинг',
        'SRD' => 'Суринамский доллар',
        'SSP' => 'Южносуданский фунт',
        'STN' => 'Добра Сан-Томе и Принсипи',
        'SVC' => 'Сальвадорский колон',
        'SYP' => 'Сирийский фунт',
        'SZL' => 'Свазилендский лилангени',
        'THB' => 'Тайский бат',
        'TJS' => 'Таджикский сомони',
        'TMT' => 'Туркменский манат',
        'TND' => 'Тунисский динар',
        'TOP' => 'Тонганская паанга',
        'TRY' => 'Турецкая лира',
        'TTD' => 'Доллар Тринидада и Тобаго',
        'TWD' => 'Новый тайваньский доллар',
        'TZS' => 'Танзанийский шиллинг',
        'UAH' => 'Украинская гривна',
        'UGX' => 'Угандийский шиллинг',
        'USD' => 'Доллар США',
        'USN' => 'Доллар США (на след. день)',
        'UYI' => 'Уругвайское песо (URUIURUI)',
        'UYU' => 'Уругвайское песо',
        'UZS' => 'Узбекский сум',
        'VES' => 'Венесуэльский боливар',
        'VND' => 'Вьетнамский донг',
        'VUV' => 'Вануатский вату',
        'WST' => 'Самоанская тала',
        'XAF' => 'Франк КФА (BEAC)',
        'XCD' => 'Восточно-карибский доллар',
        'XDR' => 'Специальные права заимствования',
        'XOF' => 'Франк КФА (BCEAO)',
        'XPF' => 'Франк КФП',
        'XSU' => 'Сукре',
        'XUA' => 'Условная единица АБР',
        'YER' => 'Йеменский риал',
        'ZAR' => 'Южноафриканский ранд',
        'ZMW' => 'Замбийская квача',
        'ZWL' => 'Зимбабвийский доллар',
    ];

    private const array NUMERIC_CODES = [
        'AED' => '784',
        'AFN' => '971',
        'ALL' => '008',
        'AMD' => '051',
        'ANG' => '532',
        'AOA' => '973',
        'ARS' => '032',
        'AUD' => '036',
        'AWG' => '533',
        'AZN' => '944',
        'BAM' => '977',
        'BBD' => '052',
        'BDT' => '050',
        'BGN' => '975',
        'BHD' => '048',
        'BIF' => '108',
        'BMD' => '060',
        'BND' => '096',
        'BOB' => '068',
        'BOV' => '984',
        'BRL' => '986',
        'BSD' => '044',
        'BTN' => '064',
        'BWP' => '072',
        'BYN' => '933',
        'BZD' => '084',
        'CAD' => '124',
        'CDF' => '976',
        'CHE' => '947',
        'CHF' => '756',
        'CHW' => '948',
        'CLF' => '990',
        'CLP' => '152',
        'CNY' => '156',
        'COP' => '170',
        'COU' => '970',
        'CRC' => '188',
        'CUC' => '931',
        'CUP' => '192',
        'CVE' => '132',
        'CZK' => '203',
        'DJF' => '262',
        'DKK' => '208',
        'DOP' => '214',
        'DZD' => '012',
        'EGP' => '818',
        'ERN' => '232',
        'ETB' => '230',
        'EUR' => '978',
        'FJD' => '242',
        'FKP' => '238',
        'GBP' => '826',
        'GEL' => '981',
        'GHS' => '936',
        'GIP' => '292',
        'GMD' => '270',
        'GNF' => '324',
        'GTQ' => '320',
        'GYD' => '328',
        'HKD' => '344',
        'HNL' => '340',
        'HTG' => '332',
        'HUF' => '348',
        'IDR' => '360',
        'ILS' => '376',
        'INR' => '356',
        'IQD' => '368',
        'IRR' => '364',
        'ISK' => '352',
        'JMD' => '388',
        'JOD' => '400',
        'JPY' => '392',
        'KES' => '404',
        'KGS' => '417',
        'KHR' => '116',
        'KMF' => '174',
        'KPW' => '408',
        'KRW' => '410',
        'KWD' => '414',
        'KYD' => '136',
        'KZT' => '398',
        'LAK' => '418',
        'LBP' => '422',
        'LKR' => '144',
        'LRD' => '430',
        'LSL' => '426',
        'LYD' => '434',
        'MAD' => '504',
        'MDL' => '498',
        'MGA' => '969',
        'MKD' => '807',
        'MMK' => '104',
        'MNT' => '496',
        'MOP' => '446',
        'MRU' => '929',
        'MUR' => '480',
        'MVR' => '462',
        'MWK' => '454',
        'MXN' => '484',
        'MXV' => '979',
        'MZN' => '943',
        'NAD' => '516',
        'NGN' => '566',
        'NIO' => '558',
        'NOK' => '578',
        'NPR' => '524',
        'NZD' => '554',
        'OMR' => '512',
        'PAB' => '590',
        'PEN' => '604',
        'PGK' => '598',
        'PHP' => '608',
        'PKR' => '586',
        'PLN' => '985',
        'PYG' => '600',
        'QAR' => '634',
        'RON' => '946',
        'RSD' => '941',
        'RUB' => '643',
        'RWF' => '646',
        'SAR' => '682',
        'SBD' => '090',
        'SCR' => '690',
        'SDG' => '938',
        'SEK' => '752',
        'SGD' => '702',
        'SHP' => '654',
        'SLL' => '694',
        'SOS' => '706',
        'SRD' => '968',
        'SSP' => '728',
        'STN' => '930',
        'SVC' => '222',
        'SYP' => '760',
        'SZL' => '748',
        'THB' => '764',
        'TJS' => '972',
        'TMT' => '934',
        'TND' => '788',
        'TOP' => '776',
        'TRY' => '949',
        'TTD' => '780',
        'TWD' => '901',
        'TZS' => '834',
        'UAH' => '980',
        'UGX' => '800',
        'USD' => '840',
        'USN' => '997',
        'UYI' => '940',
        'UYU' => '858',
        'UZS' => '860',
        'VES' => '928',
        'VND' => '704',
        'VUV' => '548',
        'WST' => '882',
        'XAF' => '950',
        'XCD' => '951',
        'XDR' => '960',
        'XOF' => '952',
        'XPF' => '953',
        'XSU' => '994',
        'XUA' => '965',
        'YER' => '886',
        'ZAR' => '710',
        'ZMW' => '967',
        'ZWL' => '932',
    ];

    public function getLocalizedName(string $locale = 'ru'): string
    {
        return match ($locale) {
            'ru' => self::NAMES_RU[$this->value] ?? $this->value,
            'en' => self::NAMES_EN[$this->value] ?? $this->value,
            default => throw new InvalidArgumentException("Unsupported locale: {$locale}"),
        };
    }

    public function getNumericCode(): string
    {
        return self::NUMERIC_CODES[$this->value];
    }

    public function jsonSerialize(): string
    {
        return $this->value;
    }
}
